import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/layout/navbar/Navbar";
import "./globals.css";
import { Toolset } from "@/components/layout/Toolset/Toolset";
import TransactionProvider from "@/contexts/TransactionContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TransactionProvider>
        <Navbar />
        <Toolset />
        {children}
        </TransactionProvider>
      </body>
    </html>
  );
}
